---
- name: Ensure .ssh directory exists for user '{{ target_user }}'
  become: true
  become_user: "{{ user.accname }}"
  ansible.builtin.file:
    path: "{{ user.homedir }}/.ssh"
    state: directory
    owner: "{{ user.accname }}"
    group: "{{ user.accname }}"
    mode: "0700"

- name: Generate SSH keypair for user '{{ user.accname }}'
  become: true
  become_user: "{{ user.accname }}"
  ansible.builtin.openssh_keypair:
    path: "{{ user.homedir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ user.accname }}"
    group: "{{ user.accname }}"
    force: "{{ user.keygen_force }}"
    mode: "0600"
  when: user.keygen | default(false)
