---
# MPS
mps:
  # Common
  version: "0.0.1"

  # Timezone
  timezone: "Europe/Berlin"

  # User
  home_dir: "{{ target_user_dir }}"

  # -- SRC
  src_etcfiles: "../templates/etc"
  src_dotfiles: "../templates/dotfiles"
  src_grubfiles: "../templates/grub"
  src_iconfiles: "../templates/grub/icons"
  src_themefiles: "../templates/grub/themes"
  src_images: "../templates/images/wallpaper"
  src_snippets: "../templates/snippets"

  # -- DST
  dst_grub: "/boot/grub"
  dst_themefiles: "/boot/grub/themes"
  dst_iconfiles: "/boot/grub/icons"
  dst_images: "/usr/share/images/mps"
  dst_qtile_repo: "/usr/share/mps/tools/qtile"
  dst_snippets: "{{ target_user_dir }}/mps/snippets"
  dst_mpsnvim: "{{ target_user_dir }}/mps/repo/github/odem/mps"
  dst_unity_key: "/usr/share/keyrings/Unity_Technologies_ApS.gpg"
  dst_nvidia_mok_key: "/var/lib/dkms/mok.pub"
  dst_dxvk_repo: "/opt/dxvk"
  dst_lutris_runtime: "{{ target_user_dir }}/.local/share/lutris/runtime"
  dst_docker_keyring_dir: /etc/apt/keyrings
  dst_docker_key: /etc/apt/keyrings/docker.asc
  dst_docker_list: /etc/apt/sources.list.d/docker.list
  dst_docker_root: /opt/docker
  dst_fontdir: /usr/share/fonts
  dst_user_font_dir: "{{ target_user_dir }}/.local/share/fonts"
  dst_tools: "/usr/share/mps/tools"
  dst_rustup_sh: "/usr/share/mps/tools/rustup/rustup.sh"
  dst_neovim: "/usr/share/mps/tools/nvim"
  dst_lazygit: "/usr/share/mps/tools/lazygit"

  # -- URL
  url_qtile: "https://github.com/qtile/qtile"
  url_ohmyzsh: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
  url_mpsnvim: "https://github.com/odem/mps-nvim.git"
  url_dotnet: "https://dot.net/v1/dotnet-install.sh"
  url_spotify_key: "https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg"
  url_spotify_repo: "http://repository.spotify.com"
  url_dotnet_installer: "https://dot.net/v1/dotnet-install.sh"
  url_unity_key: "https://hub.unity3d.com/linux/keys/public"
  url_unity_repo: "https://hub.unity3d.com/linux/repos/deb"
  url_deb_vscode: "https://go.microsoft.com/fwlink/?LinkID=760868"
  url_lutris_repo: "https://download.opensuse.org/repositories/home:/strycore/Debian_12/"
  url_lutris_sources: "/etc/apt/sources.list.d/lutris.list"
  url_lutris_key_url: "https://download.opensuse.org/repositories/home:/strycore/Debian_12/Release.key"
  url_lutris_key_path: "/etc/apt/keyrings/lutris.gpg"
  url_dxvk_repo: "https://github.com/doitsujin/dxvk.git"
  url_docker_gpg: https://download.docker.com/linux/debian/gpg
  url_docker_repo: https://download.docker.com/linux/debian
  url_rustup: "https://sh.rustup.rs"
  url_neovim: "https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.tar.gz"

  # -- Desktop
  dsk_essentials:
    - ".gtkrc-2.0"
    - ".config/Thunar"
    - ".config/gtk-2.0"
    - ".config/gtk-3.0"
  dsk_snippets:
    - "autostart.sh"
    - "autostart_clean.sh"
  dsk_default_config:
    - .config/dconf
    - .config/dunst
    - .config/gedit
    - .config/volumeicon
    - .config/birdtray-config.json
    - .config/picom.conf

  # -- Rofi
  rofi_snippets:
    - "rofi-boot-dwmswitch.sh"
    - "rofi-boot-launcher.sh"
    - "rofi-boot-powermenu.sh"

  # -- Lightdm
  lightdm_wallpaper: "wormhole.jpg"

  # -- Grub
  grub_theme: anon
  grub_icon: light
  grub_icons:
    - light
  grub_themes:
    - anon
    - showroom

  # -- Grub
  mps_folders:
    - scratch
    - snippets
    - iso
    - repo
    - tools
    - vm
    - disks
    - docs
    - wsp
    - secrets
    - venv
    - vpn

  # -- Shell
  zsh_plugins:
    zsh-bat: "https://github.com/fdellwing/zsh-bat.git"
    zsh-you-should-use: "https://github.com/MichaelAquilina/zsh-you-should-use.git"
    zsh-syntax-highlighting: "https://github.com/zsh-users/zsh-syntax-highlighting"
    zsh-autosuggestions: "https://github.com/zsh-users/zsh-autosuggestions"
  zsh_files:
    - .zshrc
  tmux_files:
    - .config/tmux
  tmuxinator_files:
    - .config/tmuxinator
  other_dotfiles:
    - dconf
    - dunst
    - gedit
    - gtk-2.0
    - gtk-3.0
    - kitty
    - Thunar
    - volumeicon

    # -- Git
  git_config:
    - .gitconfig

  # -- Editors
  vim_files:
    - .vimrc
  nvim_files:
    - .config/nvim

  # -- Locale
  locale: "en_US.UTF-8"
  kbd_model: "pc105"
  kbd_layout: "de"
  kbd_variant: "nodeadkeys"
  kbd_options: "compose:menu"
  console_charset: "UTF-8"
  console_codeset: "Lat15"
  console_fontface: "Terminus"
  console_fontsize: "8x16"
