- name: Copy bash config
  ansible.builtin.copy:
    src: "{{ mps.src_dotfiles }}/.bashrc"
    dest: "{{ mps.home_dir }}/"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"

- name: Copy bash config
  ansible.builtin.copy:
    src: "{{ mps.src_dotfiles }}/.config/bashrc"
    dest: "{{ mps.home_dir }}/.config"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"

- name: Check if .bash_logout exists
  ansible.builtin.stat:
    path: "{{ target_user_dir }}/.bash_logout"
  register: bash_logout_stat

- name: Copy .bash_logout to a custom location
  ansible.builtin.copy:
    src: "{{ target_user_dir }}/.bash_logout"
    dest: "{{ target_user_dir }}/.config/bashrc/.bash_logout"
    remote_src: true
    mode: "0700"
  when: bash_logout_stat.stat.exists

- name: Remove the original .bash_logout file
  ansible.builtin.file:
    path: "{{ target_user_dir }}/.bash_history"
    state: absent

- name: Remove the original .bash_logout file
  ansible.builtin.file:
    path: "{{ target_user_dir }}/.bash_logout"
    state: absent

- name: Remove old bashrc_alias file
  ansible.builtin.file:
    path: "{{ target_user_dir }}/.bashrc_aliases"
    state: absent

- name: Remove old bash_alias file
  ansible.builtin.file:
    path: "{{ target_user_dir }}/.bash_aliases"
    state: absent

- name: Set bash as default shell
  ansible.builtin.shell:
    cmd: "chsh -s /bin/bash {{ target_user }}"
  become: true

- name: Set kitty as default terminal
  ansible.builtin.shell:
    cmd: "update-alternatives --set x-terminal-emulator /usr/bin/kitty"
