---
- name: Get list of identity names for this host
  ansible.builtin.set_fact:
    host_config: >-
      {{
        config_hosts.hosts[inventory_hostname]
        if inventory_hostname in config_hosts.hosts
        else config_defaults.hosts[inventory_hostname]
      }}
  no_log: "{{ respect_nolog }}"

- name: Handle config users
  include_tasks: tmux.yml
  loop: "{{ host_config.users }}"
  loop_control:
    loop_var: hostuser
  when: target_user == "all"
  no_log: "{{ respect_nolog }}"

- name: Handle config users
  include_tasks: zsh.yml
  loop: "{{ host_config.users }}"
  loop_control:
    loop_var: hostuser
  when: target_user == "all" and enable_install_zsh
  no_log: "{{ respect_nolog }}"
