- name: Copy tmux config
  ansible.builtin.copy:
    src: "{{ src_dotfiles }}/{{ item }}"
    dest: "{{ target_user_dir }}/.config"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"
  loop: "{{ tmux_files }}"
  when: tmux_files is defined

- name: Copy tmuxinator config
  ansible.builtin.copy:
    src: "{{ src_dotfiles }}/{{ item }}"
    dest: "{{ target_user_dir }}/.config"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"
  loop: "{{ tmuxinator_files }}"
  when: tmuxinator_files is defined
