---
- name: Include essential apt packages
  ansible.builtin.include_tasks: apt-sources.yml
- name: Include essential apt auto-upgrades
  ansible.builtin.include_tasks: apt-auto-upgrades.yml
- name: Include locale
  ansible.builtin.include_tasks: locale.yml
- name: Include time
  ansible.builtin.include_tasks: time.yml
