---
- name: Get list of identity names for this host
  ansible.builtin.set_fact:
    host_config: >-
      {{
        config_hosts.hosts[inventory_hostname]
        if inventory_hostname in config_hosts.hosts
        else config_defaults.hosts[inventory_hostname]
      }}

- name: Include rofi essential apt packages
  ansible.builtin.include_tasks: essentials.yml

- name: Handle rofi config users
  include_tasks: config.yml
  loop: "{{ host_config.users }}"
  loop_control:
    loop_var: hostuser
  when: target_user == "all"
  no_log: "{{ respect_nolog }}"
