---
- name: Get list of identity names for this host
  ansible.builtin.set_fact:
    host_config: >-
      {{
        config_hosts.hosts[inventory_hostname]
        if inventory_hostname in config_hosts.hosts
        else config_defaults.hosts[inventory_hostname]
      }}

- name: Include gaming essential apt packages
  ansible.builtin.include_tasks: essentials.yml
- name: Include nvidia essential apt packages
  ansible.builtin.include_tasks: nvidia.yml
# - name: Include lutris packages
#   ansible.builtin.include_tasks: lutris.yml
# - name: Include dxvk packages
#   ansible.builtin.include_tasks: dxvk.yml

- name: Handle nvidia config users
  include_tasks: nvidia.yml
  loop: "{{ host_config.users }}"
  loop_control:
    loop_var: hostuser
  when: target_user == "all"
  no_log: "{{ respect_nolog }}"
