---
- name: Ensure Version
  copy:
    src: "/usr/share/plymouth/themes/joy/"
    dest: "/usr/share/plymouth/themes/{{ grub_theme }}/"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Ensure plymouth script
  copy:
    src: "/usr/share/plymouth/themes/joy/joy.plymouth"
    dest: "/usr/share/plymouth/themes/{{ grub_theme }}/{{ grub_theme }}.plymouth"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Ensure theme script
  copy:
    src: "/usr/share/plymouth/themes/joy/joy.script"
    dest: "/usr/share/plymouth/themes/{{ grub_theme }}/{{ grub_theme }}.script"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Replace string in a file
  ansible.builtin.replace:
    path: "/usr/share/plymouth/themes/{{ grub_theme }}/{{ grub_theme }}.script"
    regexp: "joy"
    replace: "{{ grub_theme }}"

- name: Replace string in a file
  ansible.builtin.replace:
    path: "/usr/share/plymouth/themes/{{ grub_theme }}/{{ grub_theme }}.plymouth"
    regexp: "joy"
    replace: "{{ grub_theme }}"

- name: Ensure Version
  copy:
    src: "/boot/grub/themes/{{ grub_theme }}/background.png"
    dest: "/usr/share/plymouth/themes/{{ grub_theme }}/"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Set theme {{ grub_theme }}
  ansible.builtin.command:
    cmd: "plymouth-set-default-theme {{ grub_theme }}"
  become: true

- name: Rebuild initrd
  ansible.builtin.command:
    cmd: "plymouth-set-default-theme -R"
  become: true
