---
- name: Setup mps optimizations
  hosts: hive
  become: true
  roles:
    # - optimize-grubmenu
    # - optimize-lightdm
    - optimize-plymouth
    # - optimize-ramdisks
    # - optimize-zram
    # - optimize-tty
