---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Reconfigure unattended-upgrades non-interactively
  ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: false

- name: Ensure stable-updates line is present in unattended-upgrades config
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "^Unattended-Upgrade::Allowed-Origins"
    line: '        "Debian stable-updates";'
    state: present

- name: Configure 20auto-upgrades for unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"

- name: Enable and start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    enabled: true
    state: started

- name: Enable and start apt-daily-upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    enabled: true
    state: started
