---
- name: Essentials OS
  ansible.builtin.apt:
    name:
      - build-essential
      - auditd
      - git
      - autoconf
      - automake
      - libtool
      - pkg-config
      - libauparse-dev
      - libcap-ng-dev
      - libev-dev
      - swig
    state: present
  become: true

# - name: Clone audit-userspace repository
#   git:
#     repo: "{{ audit_repo }}"
#     dest: "{{ audit_src_dir }}"
#     version: master
#     force: true
#
# - name: Run autoreconf
#   command: autoreconf -i
#   args:
#     chdir: "{{ audit_src_dir }}"
#
# - name: Configure audit-userspace (zos remote)
#   command: ./configure --prefix=/usr --localstatedir=/var --disable-zos-remote
#   args:
#     chdir: "{{ audit_src_dir }}"
#
# - name: Build audit-userspace
#   command: make
#   args:
#     chdir: "{{ audit_src_dir }}"
#
# - name: Install audit-userspace
#   command: make install
#   args:
#     chdir: "{{ audit_src_dir }}"
#
# - name: Ensure autrace is available in PATH
#   stat:
#     path: /usr/bin/autrace
#   register: autrace_bin

- name: Ensure autrace rules path
  file:
    path: /etc/audit/rules.d
    state: "directory"
    owner: root
    group: root
    mode: "0755"

  register: autrace_bin

- name: Ensure auditd run directory exists
  file:
    path: "{{ audit_run_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create minimal auditd configuration
  copy:
    dest: /etc/audit/auditd.conf
    content: |
      log_file = {{ audit_log_file }}
      log_format = RAW
      flush = INCREMENTAL
      freq = 50
      max_log_file = 8
      max_log_file_action = ROTATE
      space_left = 75
      space_left_action = SYSLOG
      admin_space_left = 50
      admin_space_left_action = SUSPEND
      disk_full_action = SUSPEND
      disk_error_action = SUSPEND
    owner: root
    group: root
    mode: "0755"

- name: Create audit runtime directory
  file:
    path: "/var/run/audit"
    state: directory
    owner: root
    group: root
    mode: "0755"
# - name: Ensure audit runtime directory exists
#   file:
#     path: "/usr/lib/systemd/system/auditd.service.d/"
#     state: directory
#     owner: root
#     group: root
#     mode: "0755"
#
# - name: Create systemd override for auditd
#   copy:
#     dest: /usr/lib/systemd/system/auditd.service.d/override.conf
#     content: |
#       [Service]
#       Environment="localstatedir={{ localstatedir }}"
#
#       [Unit]
#       StartLimitBurst=0
#     owner: root
#     group: root
#     mode: "0755"
