---
- name: Ensure Rustup directory exists
  ansible.builtin.file:
    path: "{{ dst_tools }}/rustup"
    state: directory
    mode: "0755"

- name: Download rustup installation script
  ansible.builtin.get_url:
    url: "{{ url_rustup }}"
    dest: "{{ dst_rustup_sh }}"
    mode: "0755"

- name: Run rustup installation script if not already installed
  ansible.builtin.shell:
    cmd: "{{ dst_rustup_sh }} -y"
    creates: "{{ target_user_dir }}/.cargo/env"
  become: true
  become_user: "{{ target_user }}"

- name: Add Rust to PATH in .bashrc if not already present
  ansible.builtin.lineinfile:
    path: "{{ target_user_dir }}/.bashrc"
    line: 'export PATH="$PATH:$HOME/.cargo/bin"'
    state: present
    insertafter: EOF
  become: true
  become_user: "{{ target_user }}"

- name: Check if cargo tools are already installed
  ansible.builtin.stat:
    path: "{{ target_user_dir }}/.cargo/bin/fd"
  register: cargo_fd

- name: Install Cargo tools only if not already installed
  ansible.builtin.shell: |
    source {{ target_user_dir }}/.cargo/env
    cargo install fd-find yazi-fm yazi-cli
  args:
    executable: /bin/bash
  environment:
    CARGO_HOME: "{{ target_user_dir }}/.cargo"
    PATH: "{{ target_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"
  when: not cargo_fd.stat.exists
  become: true
  become_user: "{{ target_user }}"
