---
- name: Get list of identity names for this host
  ansible.builtin.set_fact:
    user: >-
      {{
        users
        | selectattr('name', 'equalto', hostuser)
        | selectattr('config_terminal', 'equalto', true)
        | list
        | first
        | default({}, true)
      }}
  no_log: "{{ respect_nolog }}"

- name: Copy bash config if needed
  block:
    - name: Copy nvim config
      ansible.builtin.copy:
        src: "{{ src_dotfiles }}/.config/nvim"
        dest: "{{ user.homedir }}/.config"
        owner: "{{ user.accname }}"
        group: "{{ user.accname }}"
        mode: "0700"

    - name: Create session folder
      ansible.builtin.file:
        path: "{{ user.homedir }}/.config/nvim-session"
        state: directory
        owner: "{{ user.accname }}"
        group: "{{ user.accname }}"
        mode: "0700"
  when: user != {}
