- name: Copy nvim config
  ansible.builtin.copy:
    src: "{{ src_dotfiles }}/.config/nvim"
    dest: "{{ target_user_dir }}/.config"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"
